#@TYPE: Machine
#@NAME: Nvidia Jetson Orin NX 16GB (P3767-0000)
#@DESCRIPTION: Nvidia Jetson Orin NX 16GB module in P3509 carrier


#P3509 carrier maybe these should be changed as well

require conf/machine/p3768-0000-p3767-0000.conf


#Mods
KERNEL_DEVICETREE = "nru50p-onx8.dtb"
TEGRA_FLASHVAR_PMC_CONFIG ?= "Orin-nru50+-padvoltage-default.dtsi"
TEGRA_FLASHVAR_PINMUX_CONFIG = "Orin-nru50+-pinmux.dtsi"
BPFDTB_FILE_PINMUX_CONFIG = "Orin-nru50+-pinmux.dtsi"
EMMC_CFG="flash_t234_qspi_sd.xml";
TBCDTB_FILE="${KERNEL_DEVICETREE}";
OVERLAY_DTB_FILE+=",tegra234-p3768-0000+p3767-0000-dynamic.dtbo";
